### PR TITLE
batched shadows

### PR DESCRIPTION
**Pull request by thecozies**

### CODE REVIEW

**Comment by gheskett** [comment]
wrong repo 👀

**Comment by thecozies** [comment]
@gheskett hey it's isolated enough for cherry picking lmao

**Comment by thecozies** [comment]
also for some reason GitHub automatically requested you for review lol

**Comment by gheskett** [comment]
Probably the codeowners file

**Comment by thecozies** [comment]
LMAO oh shit

**Comment by thecozies** [comment]
you own every repo

**Comment by thecozies** [comment]
@Mr-Wiseguy used to but we kicked him out

**Comment by Mr-Wiseguy** [comment]
👨‍🌾

**Comment by thecozies** [comment]
GTFO FARM BOY

**Review by Reonu — APPROVED** [review]
Approving just in case

**Pull request merged**
